[package]
name = "kms"
version = "0.1.0"
authors = [
    "Omer <omer@kzencorp.com>",
    "Gary <gary@kzencorp.com>"
]

[lib]
crate-type = ["lib"]

[dependencies]
rust-gmp = "0.5.0"
rand = "0.5"
serde = "1.0"
serde_derive = "1.0"

[dependencies.paillier]
git = "https://github.com/mortendahl/rust-paillier"

[dependencies.zk-paillier]
git = "https://github.com/KZen-networks/zk-paillier"

[dependencies.multi-party-schnorr]
git = "https://github.com/KZen-networks/multi-party-schnorr"

[dependencies.curv]
git = "https://github.com/KZen-networks/curv"
features =  ["curvesecp256k1"]

[dependencies.multi-party-ecdsa]
git = "https://github.com/KZen-networks/multi-party-ecdsa"

[dependencies.centipede]
git = "https://github.com/KZen-networks/centipede"




[patch.crates-io]
rust-gmp = { version = "0.5.0", features = ["serde_support"], git = "https://github.com/KZen-networks/rust-gmp" }
